version: "3.8"

services:
  books_app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: books_appai
    depends_on:
      - db
      - ollama
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:superuser@db:5432/books_db
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app
    restart: always
    command: >
      sh -c "sleep 10 && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"


  db:
    image: postgres:15
    container_name: books_postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # Persist downloaded models
    restart: always
    command: ["serve"]

volumes:
  pg_data:
  ollama_data: