"""add summary column for ai summary

Revision ID: b692dcf429be
Revises: 24489bfd54c4
Create Date: 2025-03-26 17:28:21.184967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b692dcf429be'
down_revision: Union[str, None] = '24489bfd54c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('summary_ai', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'summary_ai')
    # ### end Alembic commands ###
